# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-10-29 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbasket', '0088_auto_20180610_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directiva',
            name='puesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='texto',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='titulo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
